Repository ft-transcendence-seoul/backend, pull requests merged in 2023-11, with the labels that each got.

#3 Feature/#2 docker 구현
  Dockerfile
  package.json
  src/configs/session.config.ts
Labels: bug

#7 Fix: signIn핸들러 쿼리 매개변수 받도록 수정, 그 외 오류 몇 개 수정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/main.ts
  src/test.service.ts
Labels: bug, Fix

#9 Feature/#4 class validation pipe 추가
  package.json
  src/main.ts
Labels: enhancement

#10 Fix/#8 user relation서비스 오류 개선 및 리팩토링
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.service.ts
  src/configs/session.config.ts
  src/configs/typeorm.config.ts
  src/main.ts
  src/user-relation/dtos/create-user-relation.dto.ts
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.service.ts
Labels: bug, enhancement, Fix

#19 Feature/#6 response보낼때 재사용가능한 serializer구현
  src/interceptors/serializer.interceptor.ts
Labels: enhancement

#18 Feat: https반영
  .dockerignore
  .env
  .gitignore
  docker-compose.yml
  secrets/cert.pem
  secrets/key.pem
  src/main.ts
Labels: enhancement

#22 내 정보조회API 오류 해결 및 기타 버그 수정
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/user.decorator.ts
  src/users/users.controller.ts
Labels: Fix

#27 Bug/#24 users 및 user relation 모듈 관련 api 테스트 및 버그 개선
  src/user-relation/user-relation.service.ts
Labels: bug

#31 redis 분리 및 db 초기화 문제 해결
  .prettierrc
  package-lock.json
  package.json
  src/app.module.ts
  src/commons/commons.module.ts
  src/commons/redis-client.service.ts
  src/configs/cors.config.ts
  src/configs/session.config.ts
  src/configs/typeorm.config.ts
  src/main.ts
  src/test.service.ts
Labels: bug, Refactoring

#23 Feature/#1 channel 모듈 구현
  package-lock.json
  package.json
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/dto/channel.dto.ts
  src/channels/entities/channel-invitation.entity.ts
  src/channels/entities/channel-relation.entity.ts
  src/channels/entities/channel.entity.ts
  src/pipes/ChannelById.Pipe.ts
  src/users/user.entity.ts
Labels: enhancement

#36 Test: 테스트 유저 생성 오류 수정
  src/test.service.ts
Labels: bug

#33 Bug/#24 users 및 user relation 모듈 관련 api 테스트 및 버그 개선
  src/user-relation/dtos/show-friend-relations.dto.ts
  src/user-relation/dtos/show-friends.dto.ts
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.service.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: bug, Fix

#35 Feature/#1 channel 모듈 구현 API 테스트 완료
  package-lock.json
  package.json
  src/app.module.ts
  src/channels/channels.controller.ts
  src/channels/channels.guard.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/channel.dto.ts
Labels: enhancement, Fix

#38 Feature/#13 dm 모듈 구현소켓
  src/app.module.ts
  src/commons/commons.module.ts
  src/commons/main.gateway.ts
  src/commons/redis-client.service.ts
  src/direct-messages/direct-messages.gateway.ts
  src/direct-messages/direct-messages.module.ts
  src/direct-messages/direct-messages.service.ts
  src/direct-messages/dtos/direct-message-receive.dto.ts
  src/direct-messages/dtos/direct-message.dto.ts
  src/direct-messages/dtos/unread-message-raw.dto.ts
  src/direct-messages/dtos/unread-message.dto.ts
  src/direct-messages/entitys/direct-message.entity.ts
  src/filters/websocket-exception.fileter.ts
  src/interceptors/serializer.interceptor.ts
  src/users/dto/show-user-overview.dto.ts
Labels: enhancement

#44 Bug: user-relation서비스 메서드 일부에서 메서드 요청자가 자기 자신과 상호작용을 하지 못하도록 예외처리 추가함
  package-lock.json
  package.json
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.entity.ts
  src/user-relation/user-relation.service.ts
Labels: bug, Fix

#45 Feature: 유저가 접속한 채널과 각 채널의 역할 조회, ChannelByIdPipe, UserByIdPipe로 예외 처리 등등
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/entities/channel-relation.entity.ts
Labels: enhancement, Fix, Refactoring

#48 Fix: @Get('me') API 반환 클래스에 유저 아이디 필드 추가
  src/users/dto/show-user-information.ts
  src/users/users.controller.ts
Labels: Fix

#49 Feature: mute 기능 추가
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/entities/channel-relation.entity.ts
Labels: enhancement, Refactoring

#50 Fix: 소켓 인증 방식 cookie에서 authorization헤더로 변경
  src/commons/main.gateway.ts
  src/configs/cors.config.ts
  src/direct-messages/dtos/direct-message.dto.ts
Labels: Fix

#55 Feat/#54 user 및 user relation모듈 로직 추가
  src/app.module.ts
  src/notifications/notification.entity.ts
  src/notifications/notifications.controller.ts
  src/notifications/notifications.module.ts
  src/notifications/notifications.service.ts
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.entity.ts
  src/user-relation/user-relation.service.ts
  src/users/dto/show-user-details.dto.ts
  src/users/dto/show-user-information.ts
  src/users/dto/show-user-overview.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/enums/avatar.enum.ts
  src/users/user.entity.ts
  src/users/users.module.ts
Labels: enhancement, Fix

#53 Feat/#28 로그인 2차 인증 구현하기
  .env
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/secure-shield/dtos/totp.dto.ts
  src/secure-shield/secure-shield.module.ts
  src/secure-shield/secure-shield.service.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/show-user-details.dto.ts
  src/users/dtos/show-user-information.ts
  src/users/dtos/show-user-overview.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#56 Feature/#14 알림notification 기능 구현 및 Feature/#15 Channel 소켓 구현
  .gitignore
  src/app.module.ts
  src/channels/channels-emit.gateway.ts
  src/channels/channels.controller.ts
  src/channels/channels.guard.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-member-update.dto.ts
  src/channels/dto/channel-message.dto.ts
  src/channels/dto/channel-relation.dto.ts
  src/commons/commons.module.ts
  src/commons/enums/redis.enum.ts
  src/commons/main.gateway.ts
  src/commons/redis-client.service.ts
  src/direct-messages/direct-messages.module.ts
  src/direct-messages/dtos/direct-message.dto.ts
  src/interceptors/serializer.interceptor.ts
  src/notifications/dtos/noti-channel-invite.dto.ts
  src/notifications/dtos/noti-friend-request.dto.ts
  src/notifications/enums/notification.enum.ts
  src/notifications/notifications-emit.gateway.ts
  src/notifications/notifications.module.ts
  src/user-relation/user-relation.module.ts
  src/user-relation/user-relation.service.ts
  src/utils/dtoSerializer.util.ts
  src/websocket-listening/gateways/channel-listening.gateway.ts
  src/websocket-listening/gateways/dm-listening.gateway.ts
  src/websocket-listening/gateways/main-listening.gateway.ts
  src/websocket-listening/gateways/notification-listening.gateway.ts
  src/websocket-listening/websocket-listening.module.ts
Labels: enhancement, Fix

#58 Bug/#57 auth controller의 redirect user메서드 버그 개선
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: bug, Fix

#59 Feature/#14 알림notification 기능 구현
  src/channels/channels-emit.gateway.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-member-update.dto.ts
  src/channels/dto/channel-relation.dto.ts
  src/channels/dto/channel.dto.ts
  src/direct-messages/direct-messages.service.ts
  src/direct-messages/dtos/unread-message.dto.ts
  src/notifications/dtos/noti-channel-invite.dto.ts
  src/notifications/dtos/noti-friend-request.dto.ts
  src/notifications/enums/notification.enum.ts
Labels: bug, Fix

#60 게임 제외 소켓완성
  src/app.module.ts
  src/channels/channels-emit.gateway.ts
  src/channels/channels.gateway.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/channel-message-emit.dto.ts
  src/channels/dto/channel-message-receive.dto.ts
  src/channels/dto/channel-message.dto.ts
  src/commons/redis-client.service.ts
  src/direct-messages/direct-messages.gateway.ts
  src/direct-messages/direct-messages.module.ts
  src/direct-messages/direct-messages.service.ts
  src/direct-messages/entities/direct-message.entity.ts
  src/notifications/notifications-emit.gateway.ts
  src/notifications/notifications.gateway.ts
  src/notifications/notifications.module.ts
  src/socket-connection/socket-connection.gateway.ts
  src/socket-connection/socket-connection.module.ts
  src/user-relation/user-relation.gateway.ts
  src/user-relation/user-relation.module.ts
  src/user-relation/user-relation.service.ts
  src/websocket-listening/gateways/channel-listening.gateway.ts
  src/websocket-listening/gateways/main-listening.gateway.ts
  src/websocket-listening/websocket-listening.module.ts
  transendence.sqlite
Labels: bug, enhancement, Fix
