Repository ft-transcendence-seoul/backend, pull requests merged in 2023-12, with the labels that each got.

#64 Fix: Get('users/me') API 반환 DTO에 is2FA 필드 추가
  src/users/users.controller.ts
Labels: Fix

#67 Refactor/#26 담당 모듈에 serialize 적용
  src/auth/auth.controller.ts
  src/direct-messages/direct-messages.gateway.ts
  src/user-relation/dtos/show-blocked-users.dto.ts
  src/user-relation/dtos/show-friend-relations.dto.ts
  src/user-relation/dtos/show-user-id.dto.ts
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.service.ts
  src/users/dtos/create-user.dto.ts
  src/users/dtos/show-user-details.dto.ts
  src/users/dtos/show-user-information.ts
  src/users/dtos/update-user.dto.ts
  src/users/user.entity.ts
  src/users/users.controller.ts
Labels: Refactoring

#78 Feature/#16 게임 모듈 구현
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.service.ts
  src/channels/channels.controller.ts
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/channels/entities/channel-invitation.entity.ts
  src/channels/entities/channel-relation.entity.ts
  src/commons/enums/redis.enum.ts
  src/commons/redis-client.service.ts
  src/direct-messages/direct-messages.gateway.ts
  src/direct-messages/entities/direct-message.entity.ts
  src/games/dtos/game-ball.dto.ts
  src/games/dtos/game-bar.dto.ts
  src/games/dtos/game-info.dto.ts
  src/games/dtos/game-mode.dto.ts
  src/games/dtos/game-player.dto.ts
  src/games/dtos/game-result.dto.ts
  src/games/dtos/game-start.dto.ts
  src/games/enums/game-mode.enum.ts
  src/games/enums/game-status.enum.ts
  src/games/enums/game-type.enum.ts
  src/games/game/games.ball.ts
  src/games/game/games.match.ts
  src/games/game/games.player.ts
  src/games/game/games.setting.ts
  src/games/games.controller.ts
  src/games/games.gateway.ts
  src/games/games.module.ts
  src/games/games.service.ts
  src/notifications/dtos/noti-game-invite.dto.ts
  src/socket-connection/enums/socket-room-prefix.enum.ts
  src/socket-connection/socket-connection.gateway.ts
  src/test.service.ts
  src/user-relation/dtos/create-user-relation.dto.ts
  src/user-relation/user-relation.controller.ts
  src/user-relation/user-relation.entity.ts
  src/user-relation/user-relation.gateway.ts
  src/user-relation/user-relation.module.ts
  src/user-relation/user-relation.service.ts
  src/users/dtos/match-history.dto.ts
  src/users/dtos/show-user-details.dto.ts
  src/users/dtos/show-user-information.ts
  src/users/entities/match-history.entity.ts
  src/users/entities/user.entity.ts
  src/users/enums/match-result.enum.ts
  src/users/enums/user-status.enum.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#80 Bug: oppense -> opponent 오타 수정 및 opponent 누락 해결
  src/games/dtos/game-info.dto.ts
  src/games/dtos/game-start.dto.ts
  src/games/games.gateway.ts
  src/games/games.service.ts
Labels: bug

#81 Feat: socket과 session을 대응시켜 중복로그인 방지 및 api에 socketConnecion가드 추가
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/channels/channels.gateway.ts
  src/commons/enums/redis.enum.ts
  src/configs/session.config.ts
  src/socket-connection/socket-connection.gateway.ts
  src/user-relation/user-relation.module.ts
  src/users/users.module.ts
Labels: enhancement

#84 Bug: 게임에 중복으로 참여하는 에러 처리
  src/games/games.controller.ts
Labels: bug

#85 Bug: auth헤더로 소켓 인증시 오류 socket.id를 찾지못하는 오류 해결
  src/socket-connection/socket-connection.gateway.ts
Labels: bug

#88 Bug: 채널생성시 join누락, block된사람 채팅 차단시 prefix누락, user default수정
  src/channels/channels.gateway.ts
  src/channels/channels.service.ts
  src/users/entities/user.entity.ts
Labels: bug

#94 Bug: axios에러 catch하지 않는 오류 수정
  src/auth/auth.controller.ts
  src/filters/axios-exception.filter.ts
Labels: bug

#92 Feat/#91 예외 처리 추가 및 파일 업로드 api 추가
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/commons/MulterConfig.service.ts
  src/users/dtos/show-user-details.dto.ts
  src/users/dtos/show-user-information.ts
  src/users/dtos/show-user-overview.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/enums/avatar.enum.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: bug, enhancement, Fix

#96 Bug: 만료된 채널 초대 알림 가는거 해결
  src/channels/channels.service.ts
Labels: bug
